# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-org
# - jemoji-plus

# Gem Settings
author: Khinshan Khan # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Khinshan Khan # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://github.com/kkhan01
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# Pagination
paginate: 5
paginate_path: blog/page/:num

# Site settings
url: 'https://khinshankhan.com'
baseurl: ''
title: 'Khinshan Khan'
description: 'This is my new website'
permalink: pretty
logo: "/assets/imgs/works/k_logo.jpeg"

disqus: "kkhan01"

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/
- title: Search
  url: /search/
- title: Resume
  url: https://kkhan01.github.io/resume/resume.pdf

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# Favicons are also used in the manifest file. Syntax is 'size: path'
favicons:
  16: '/assets/imgs/works/k_logo.jpeg'
  32: '/assets/imgs/works/k_logo.jpeg'
  96: '/assets/imgs/works/k_logo.jpeg'
  120: '/assets/imgs/works/k_logo.jpeg'
  144: '/assets/imgs/works/k_logo.jpeg'
  180: '/assets/imgs/works/k_logo.jpeg'
  512: '/assets/imgs/works/k_logo.jpeg'
  1024: '/assets/imgs/works/k_logo.jpeg'

social_links:
  GitHub: https://github.com/kkhan01
  RSS: /feed.xml


########################################################
# jemoji setting
#
# See: https://github.com/jekyll/jemoji
#
# command:
# gem install gemoji
# bundle exec gemoji extract assets/images/emoji
#
########################################################
emoji:
  # src: "/static/images/icons/emoji"
  src: "https://github.githubassets.com/images/icons/"

########################################################
# jemoji-plus setting
########################################################
jekyll_plus:
  # The emoji's image host url, 'https://github.githubassets.com' (default).
  # The trailing can't end with '/', and it's can be setting to '' (empty string).
  host: 'https://github.githubassets.com'

  # The emoji's image path of above host url, '/images/icons/' (default).
  # If it must start with '/' character, and it's can not be a empty string.
  path: '/images/icons/'

  image:
    class: 'emoji'    # The emoji's css class name. 'emoji' (default)
    ext_name: 'png'   # The emoji's image file extension. 'png' (default), 'jpg', 'jpeg', 'svg'
    width: 20         # The emoji's image width. 20 (default)
    height: 20        # The emoji's image height. 20 (default)

  format:
    #
    # [image-baseurl]: The emoji's image base URL, value = '[jemoji_plus.host][jemoji_plus.path]'
    # [image-filename]: The emoji's image file name, like: '1f371'
    # [image-extname]: The emoji's image file extension, like: 'png'
    #
    # Example:
    #
    #   https://github.githubassets.com/images/icons/emoji/unicode/1f371.png?v8
    #
    image_src: '[image-baseurl]emoji/unicode/[image-filename].[image-extname]?v8'

    #
    # [emoji-class]: The emoji's css class name, value = [jemoji_plus.image.class]
    # [emoji-name]: The emoji's alias name.
    # [emoji-image-src]: The emoji's image source url, value = [jemoji_plus.format.image_src]
    #
    # Example:
    #
    #   <img class="github-emoji" title="bento" alt="bento" src="https://github.githubassets.com/images/icons/emoji/unicode/1f371.png?v8" width="20" height="20" />
    #
    emoji_html: '<img class="[emoji-class]" title="[emoji-name]" alt="[emoji-name]" src="[emoji-image-src]" width="[emoji-width]" height="[emoji-height] />'
